### ISSUE TITLE
Space constraints

### ISSUE THREAD

**Issue by M4tt30rru** [SpartanRefactoring/spartan#3]
For space constraints, we maybe need to shrink a bit the technique section - that is, perhaps, already significantly large btw. I already gathered the techniques in separate subsections, but there are some for which I do not know if we have to mention them or not (or if their are already mentioned in the present paragraphs - I got confused by some of the notes).

**Comment by yossigil** [comment]
Most of it will die, so there is no worry. We will use the material collected there to make a dense description.
