### ISSUE TITLE
Gal's second paper

### ISSUE THREAD

**Issue by M4tt30rru** [SpartanRefactoring/spartan#4]
I was not able to find it so far.
I found the first one in dblp at this address:
http://dblp.uni-trier.de/pers/hd/l/Lalouche:Gal
There is nothing at his web page (in the Technion website), or at his Linkedin profile.
It is not cited in "When the metrics mean nothing" (at least in my pdf).
Also in your profile on dblp there is not a second paper.
Do you have any clue? Keywords, title, conference venues, journal, etc?

**Comment by yossigil** [comment]
, "On the Correlation between Size and Metric Validity", 
Journal = Empirical Software Engineering.
year=2016
Note= Manuscript \# EMSE-D-15-00163R2

**Comment by M4tt30rru** [comment]
I browsed the 2016 issues and did not find anything. It was accepted and to be published, right? Should we write "accepted"?
