### ISSUE TITLE
Add gradle support 

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/spartan#9]

**Comment by orenafek** [comment]
By adding Gradle support, you mean replacing this maven project with a gradle project?
or keeping them both?

**Comment by yossigil** [comment]
I think it is safe to keep them both for now

**Comment by orenafek** [comment]
@OriRoth 
Where are with that ?

**Comment by OriRoth** [comment]
Pretty done (umm everything except gradle build task). I'll integrate the changes later today. You can check https://github.com/OriRoth/X where we experimented (successfully!) with gradle.

Though @RoeiRaz is considering going Maven after all... talk with him about it if you want (it is related to your IntelliJ project).

In short: we can work in eclipse with gradle and do everything, but we still did not managed to run `gradle build` (need some work).

**Comment by yossigil** [comment]
Good job! 

@RoeiRaz what's up?

**Comment by RoeiRaz** [comment]
we managed to compile the intellij spartanizer using maven, as a backup solution in case we cant make the spartanizer work with gradle. I am now trying to resolve the cyclic dependency between _spartan_ and _fluent.ly_ modules

**Comment by orenafek** [comment]
@OriRoth 
Close this ?
because I cant ...

**Comment by OriRoth** [comment]
Done, see https://github.com/SpartanRefactoring/Main/issues/1309
